### ISSUE TITLE
Routing for each method

### ISSUE THREAD

**Issue by bararchy** [Codcore/Amethyst#12]
Something like this makes sense to me, but apparently isn't working as I expect (as in allowing only the first method for each vir dir) 

``` crystal
routes.draw do
      get "/",       "login#new"
      post "/",      "login#create"
      get "/login",  "login#new"
      post "/login", "login#create"
      register LoginController
end
```

Is this a bug or this is how it suppose to behave ?

**Comment by Codcore** [comment]
@bararchy Sorry, but I didn't understand question.

``` crystal
get "/login",  "login#new"
post "/login", "login#new"
```

will allow two methods for one route.

**Comment by bararchy** [comment]
I'll try to explain a little better, what I want to achive is that: 

``` crystal
      get "/login",  "login#new"
      post "/login", "login#create"
```

which means, if the client is using GET, he will get the *.new , but, if he uses POST, he will get the *.create

Does that makes sense ?

**Comment by Codcore** [comment]
@bararchy yes, this is the division of responsibility - actually, there are two different **actions**. First one  shows page for creating indentity, second is responsible of creating indentity. Actually, this is RESTFUL approach
