### ISSUE TITLE
HTTP status and version merged in response to client

### ISSUE THREAD

**Issue by bararchy** [Codcore/Amethyst#13]
From Amethyst:
Status code: 200 OK HTTP/1.1

From Google:
Status code: 200 OK
Version: HTTP/2.0

Pictures:
Amethyst:

![am](https://cloud.githubusercontent.com/assets/1631073/8267228/ee2d8114-175f-11e5-9c46-f9baf7f5b53e.png)

Google:
![goo](https://cloud.githubusercontent.com/assets/1631073/8267229/f19a49a4-175f-11e5-80ff-d6abf965cec4.png)

**Comment by Codcore** [comment]
@bararchy It is due you using `response.status=` wrong way. I changed it  to accept only a `Int32`

**Comment by bararchy** [comment]
@Codcore This is still an issue when using 

``` crystal
  def internal_error(e)
    response.set(501, "Internal Error")
    html "<p>Error executing command: #{e}</p>"
  end
```

Using curl you can see this very easy:

```
curl http://127.0.0.1:8080/command/r_stop -vv
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /command/r_stop HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 HTTP/1.1
< Content-type: text/html
< Content-length: 92
< Connection: keep-alive
< 
* Connection #0 to host 127.0.0.1 left intact
<p>Error executing command: Error connecting to '192.168.143.129:8888': No route to host</p>
```

Client shold get: `HTTP/1.1 200` , not `HTTP/1.1 200 HTTP/1.1`

**Comment by bararchy** [comment]
@Codcore Fixed via https://github.com/Codcore/Amethyst/commit/38b9eb9bff9cb21d9cd894c94cacbdcf002dc82d
