### ISSUE TITLE
The goal: "fast like Node.js"? - Crystal should be faster than node.js.

### ISSUE THREAD

**Issue by y1** [Codcore/Amethyst#16]
> The goals of Amethyst are to be fast like Node.js

Being compiled language, Crystal should be faster than Node.js. The goal should be much higher than that.

Am I missed something?

**Comment by Codcore** [comment]
@y1 yeah, we want to be much faster that node.js, and we are :smile: . I mentioned Node.js because it is in trend nowadays.

**Comment by bararchy** [comment]
@y1 @Codcore  This can be closed, the README doesn't specified Node.js anymore, also, this isn't really an issue ;)

Btw, @y1 for questions like those you can use the gitter chat :) 
https://gitter.im/Codcore/Amethyst
