### ISSUE TITLE
Unhandled exception: Error writing file: Broken pipe

### ISSUE THREAD

**Issue by bararchy** [Codcore/Amethyst#17]
Under heavy load using wrk -t 10 -c 300.
I get a Broken pipe error, then even though Amethyst is still running the socket isn't listening anymore.

**Comment by Codcore** [comment]
@bararchy https://github.com/manastech/crystal/issues/834 this is crystal http server issue. I hope it will be fixed in the next release.

**Comment by bararchy** [comment]
@Codcore Fair enough, lets leave this issue open until it will be resolved at upstream ?

**Comment by Codcore** [comment]
@bararchy of course, let see what will change

**Comment by bararchy** [comment]
This is closed thanks to Upstream https://github.com/manastech/crystal/commit/a9b00cc664b12cf595e57d6a168f10fc4807e897
Closing
