### ISSUE TITLE
IndexOutOfBounds changed to IndexError in Crystal HEAD

### ISSUE THREAD

**Issue by bararchy** [Codcore/Amethyst#23]
in line 135 of https://github.com/Codcore/Amethyst/blob/master/src/amethyst/http/request.cr
you have 

``` crystal
rescue IndexOutOfBounds
```

I changed that in my upcoming PR (https://github.com/bararchy/Amethyst/commit/2fd8766efab1a07ed6614d256b050d8ff2f62cc8) to 

``` crystal
rescue IndexError
```

This is because of PR https://github.com/manastech/crystal/pull/859

**Comment by Codcore** [comment]
@bararchy we'll change that when new version of Crystal will be released. Thanks!

**Comment by Codcore** [comment]
Fixed with 35a45078
