### ISSUE TITLE
pull from master to crystal-head branch

### ISSUE THREAD

**Issue by bararchy** [Codcore/Amethyst#42]

**Comment by rmcfadzean** [comment]
+1 now that 0.7.5 is out

**Comment by sdogruyol** [comment]
Hey @Codcore what do you think about this?

**Comment by Codcore** [comment]
@sdogruyol, I think this is good idea :)

**Comment by sdogruyol** [comment]
I actually prefer tracking master :+1:

**Comment by Codcore** [comment]
I think @bararchy meant just to update crystal-head branch

**Comment by Codcore** [comment]
Actually, I'll soon going to buy new computer, and want to return to amethyst development. So, I hope we'll make Amethyst much more powerful and better ;)

**Comment by sdogruyol** [comment]
That'd be awesome because lots of people are waiting for Amethyst :+1:

**Comment by alanwillms** [comment]
@Codcore you could plan Amethyst features using Github milestones and distribute issues with people willing to help

**Comment by sdogruyol** [comment]
Agree :+1:

**Comment by Codcore** [comment]
@alanwillms, thanks for advice. It is good idea, I will use milestones

**Comment by Codcore** [comment]
The problem is that my smartphone is not such comfortable for github as widescreen computer :laughing:

**Comment by sdogruyol** [comment]
That's for sure :smile:
