### ISSUE TITLE
What does the future of this project look like?

### ISSUE THREAD

**Issue by elorest** [Codcore/Amethyst#65]
I'd like to use this project because it seems to have one of more advanced ORMs for crystal but it looks sort of abandoned. Also I'm having issues getting it to compile with newer versions of crystal. Any suggestions?

**Comment by Xosmond** [comment]
I think we should fork this and bring it up

**Comment by bararchy** [comment]
Yeha , the maintainer does not wish to continue working on it , though , I do see he accepts PRs

**Comment by Xosmond** [comment]
Yeah, also crystal is changing a lot until the 1.0 version, maybe we should wait to that. it would be awesome that exist a Crystal on Rails

**Comment by sam0x17** [comment]
I would definitely contribute to this

**Comment by phortx** [comment]
Someone should start a crystal Rails clone with [Trailblazer](http://trailblazer.to/) architecture ... that would be some kickass framework. Just sayin ;)

**Comment by bararchy** [comment]
@Codcore , Would you be ok with moving this repo to the care of https://github.com/crystal-community ? 
I think that @crystal-community can take this project and move it forward while allowing multiple people to maintain it.

**Comment by Codcore** [comment]
@bararchy, with great pleasure, what should I do?

**Comment by veelenga** [comment]
@Codcore I have sent you an invitation to crystal-community organization. You can accept the request and transfer the repo.

/cc @benoist

**Comment by bararchy** [comment]
Awsome ! Thanks @Codcore  :)

**Comment by benoist** [comment]
Nice!

**Comment by Codcore** [comment]
@bararchy @benoist done, guys! Take care of it!

**Comment by bararchy** [comment]
@Codcore Thanks for giving us the opportunity :)

**Comment by bararchy** [comment]
@benoist @elorest or @veelenga 
I guess this issue can be closed now ?

**Comment by Codcore** [comment]
@bararchy I believe here this project will get new life. Yes, this issue can be closed now.
