### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by ghost** [Codcore/Amethyst#66]
Seems like it's been a little while....just wanted to see if this project is still active.

**Comment by fridgerator** [comment]
Doesn't seem to be, I emailed the owner of the repo a few months ago and he said he did not have time to work on it right now.

**Comment by jamessral** [comment]
I think everyone is really rallying around Kemal as well

**Comment by drujensen** [comment]
I'm still here but I haven't seen much interest in it.  Kemal seems to hit the spot for most use cases.
