### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by sdogruyol** [Codcore/Amethyst#8]
Using Crystal 0.7.3

Cloning the repo and trying to run examples with

`crystal run examples/simple_application.cr`

Gives the error

``` sh
Error in ./examples/simple_application.cr:6: while requiring "../src/amethyst"

require "../src/amethyst"
^

in ./src/amethyst.cr:1: while requiring "./amethyst/base"

require "./amethyst/base"
^

in ./src/amethyst/base/base.cr:8: while requiring "../middleware"

require "../middleware"
^

in ./src/amethyst/middleware/middleware.cr:2: while requiring "mime": can't find file 'mime' relative to '/Users/serdardogruyol/playground/Amethyst/src/amethyst/middleware'

require "mime"
^

```

**Comment by sdogruyol** [comment]
Seems like you have to install the dependencies first via

`crystal deps`

Updated the Installation GH page also.

**Comment by Codcore** [comment]
@Sdogruyol yes, dependencies must be installed first through `crystal deps`. I will add this to Readme, thank you.
